resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - features/*
    - master
    - develop
  paths:
    exclude:
    - README.md

jobs:

- job: Job_1
  displayName: Build 
  condition: succeeded()
  pool:
    name: Hosted Ubuntu 1604
    demands: npm

  variables:
    applicationName: 'cosmosScheduler123'

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.sln'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.sln'
      arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
      zipAfterPublish: False

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact drop-api'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'drop-api'


  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: 'cosmosscheduler.app'
      verbose: false

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: 'cosmosscheduler.app'
      verbose: false
      customCommand: 'run-script build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop-app'
    inputs:
      PathtoPublish: 'cosmosscheduler.app/build'
      ArtifactName: 'drop-app'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop-arm'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/CosmosScheduler.Arm'
      ArtifactName: 'drop-arm'
